# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:

- master

pool:
  vmImage: 'windows-latest'
#  demands:
#  - msbuild

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'src/Magic.Specs/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: 'tests/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/Magic.Specs/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: true

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  condition: and(succeeded(), eq(variables['publishNuget'], true))
  inputs:
    command: pack
    packagesToPack: 'src/Magic.Specs/*.csproj'
    nobuild: true

- task: DotNetCoreCLI@2
  displayName: 'Push'
  condition: and(succeeded(), eq(variables['publishNuget'], true))
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'github-connection'